import { getS } from "../crmSettings.js";
import {
  INTENT_TAGS, TAG_COLOR, OUTREACH_SOURCE, STUDIO_TYPE, CLOSE_PROB, STAGE,
  CONTRACT_STATUS, SESSION_STATUS, SETUP_STATUS, OFFER_STATUS, OFFER_PROB, SOURCE, REFERRAL,
  OUTREACH_STATUS, OUTREACH_WARMTH, OUTREACH_TARGET_TYPE, OUTREACH_RESPONSE, OUTREACH_PRIORITY,
  TESTIMONIAL_STATUS, TESTIMONIAL_TYPE, TESTIMONIAL_THEMES, TMPL_CATEGORY, TMPL_CHANNEL,
  TMPL_LINKED_TO, EXPENSE_CATEGORY, EXPENSE_PAYMENT_METHOD, EXPENSE_RECUR_FREQ, REV_CHANNEL,
  COST_CENTER, PLATFORM, CONTENT_STATUS, CONTENT_CATEGORY, CONTENT_CTA, FUTYPE, REF_STATUS, STATUS,
} from "../constants.js";

export function f(key, label, type, opts = {}) { return { key, label, type, ...opts }; }

export const FIELDS = {
  clients: [
    f("name", "Name", "text", { title: true }),
    f("phone", "Phone", "phone"), f("email", "Email", "email"),
    f("sessionsAttended", "Sessions attended", "number"),
    f("firstSession", "First session", "date"), f("lastSession", "Last session", "date"),
    f("nextSession", "Next session", "date"),
    f("notes", "Emotional notes", "textarea"),
    f("status", "Status", "select", { options: () => getS().clientStatuses }),
    f("clientType", "Client type", "select", { options: () => getS().clientTypes }),
    f("source", "Source", "select", { options: () => getS().sources }),
    f("referral", "Referral potential", "select", { options: () => getS().referralLevels }),
    f("packageType", "Package type", "select", { options: () => getS().packageTypes }),
    f("tags", "Intent tags", "multiselect", { options: INTENT_TAGS, colorMap: TAG_COLOR }),
    f("lifetimeValue", "Lifetime value", "currency"),
  ],
  partners: [
    f("name", "Studio name", "text", { title: true }),
    f("location", "Location", "text", { wide: true }),
    f("contact", "Contact name", "text"),
    f("role", "Role", "dropdown", { options: ["Owner", "Manager", "Director", "GM", "Instructor"] }),
    f("email", "Email", "email"), f("phone", "Phone", "phone"),
    f("source", "Lead source", "select", { options: OUTREACH_SOURCE }),
    f("painPoint", "Pain point", "textarea"),
    f("proposedPackage", "Proposed package", "text"),
    f("estimatedCommunitySize", "Est. community size", "number"),
    f("bestFitJourney", "Best-fit journey", "text"),
    f("revenuePotential", "Revenue potential", "currency"),
    f("studioType", "Studio type", "tagselector", { options: STUDIO_TYPE }),
    f("closeProbability", "Close probability", "select", { options: CLOSE_PROB }),
    f("stage", "Pipeline stage", "select", { options: STAGE }),
    f("studioSharePct", "Studio revenue share % (studio's cut)", "number"),
    f("contractStatus", "Contract status", "select", { options: CONTRACT_STATUS }),
    f("outreachDate", "First outreach date", "date"),
    f("lastTouch", "Last touch date", "date"),
    f("nextAction", "Next action date", "date"),
    f("avgAttendance", "Avg attendance", "number"),
    f("sessionsPerMonth", "Sessions per month", "number"),
    f("insuranceReqs", "Insurance requirements", "textarea"),
    f("promotionCommitments", "Promotion commitments", "textarea"),
    f("notes", "Conversation notes", "textarea"),
  ],
  sessions: [
    f("name", "Session name", "text", { title: true }), f("studioId", "Studio", "relation", { target: "partners" }),
    f("status", "Status", "select", { options: SESSION_STATUS }),
    f("journey", "Journey used", "select", { options: () => (getS().journeyDescriptions || []).map(j => j.name).filter(Boolean) }),
    f("date", "Date", "date"), f("time", "Time", "text"), f("durationMins", "Duration (mins)", "number"),
    f("capacity", "Room capacity", "number"), f("registered", "Registered attendees", "number"),
    f("attendance", "Actual attendance", "number"), f("paidAttendees", "Paid attendees", "number"),
    f("waivers", "Waivers completed", "number"), f("noShows", "No-shows", "number"),
    f("pricePerSeat", "Price per attendee (studio sessions)", "currency"),
    f("revenue", "Gross revenue", "currency"), f("studioSplit", "Studio split (paid out)", "currency"),
    f("netRevenue", "Your net revenue", "currency"),
    f("conversion", "Package conversion rate", "percent"), f("packagesSold", "Packages sold", "number"),
    f("referralsGenerated", "Referrals generated", "number"),
    f("testimonialsCapt", "Testimonials captured", "number"),
    f("roomSetupStatus", "Room setup status", "select", { options: SETUP_STATUS }),
    f("musicSetupStatus", "Music/headset status", "select", { options: SETUP_STATUS }),
    f("equipmentNeeded", "Equipment needed", "textarea"),
    f("breakthroughNoted", "Breakthrough noted?", "checkbox"),
    f("notes", "Session notes", "textarea"),
    f("locationAddress", "Studio Address", "text"),
    f("locationType",   "Location Type", "select", { options: ["zoom", "physical", "custom", "phone", "other"] }),
    f("locationJoinUrl","Zoom / Join URL", "text"),
    f("calendlyEventUri", "Calendly Event URI", "text"),
  ],
  offers: [
    f("name", "Offer", "text", { title: true }), f("clientId", "Client", "relation", { target: "clients" }),
    f("offerType", "Offer type", "select", { options: () => getS().offerTypes }), f("price", "Amount", "currency"),
    f("status", "Status", "select", { options: OFFER_STATUS }),
    f("probability", "Close probability", "select", { options: OFFER_PROB }),
    f("source", "Source", "select", { options: () => getS().sources }),
    f("dateOffered", "Date offered", "date"), f("expireDate", "Expiration date", "date"), f("followUpDate", "Follow-up date", "date"),
    f("notes", "Notes", "textarea"), f("reasonLost", "Reason lost", "text"),
  ],
  revenue: [
    f("name", "Description", "text", { title: true }), f("date", "Date", "date"),
    f("channel", "Channel", "select", { options: REV_CHANNEL }),
    f("gross", "Gross revenue", "currency"), f("stripeFee", "Processing fee (Stripe)", "currency"),
    f("studioSplit", "Studio split", "currency"), f("facilitatorCost", "Facilitator cost", "currency"), f("refunds", "Refunds", "currency"),
    f("source", "Source", "select", { options: SOURCE }), f("campaign", "Campaign", "text"),
    f("sessionId", "Session", "relation", { target: "sessions" }), f("clientId", "Client", "relation", { target: "clients" }),
    f("costCenter", "Cost center", "select", { options: COST_CENTER }), f("notes", "Notes", "textarea"),
  ],
  content: [
    f("name",          "Post title / idea",       "text",     { title: true }),
    f("category",      "Content category",        "select",   { options: CONTENT_CATEGORY }),
    f("status",        "Status",                  "select",   { options: CONTENT_STATUS }),
    f("platform",      "Platform",                "select",   { options: PLATFORM }),
    f("body",          "Draft / caption",         "textarea"),
    f("cta",           "Call to action",          "select",   { options: CONTENT_CTA }),
    f("scheduledDate", "Scheduled date",          "date"),
    f("datePosted",    "Published date",          "date"),
    f("sessionId",     "Session promoted",        "relation", { target: "sessions" }),
    f("partnerId",     "Studio partner tagged",   "relation", { target: "partners" }),
    f("reused",        "Repurposed content?",     "checkbox"),
    f("reach",         "Reach",                   "number"),
    f("likes",         "Likes",                   "number"),
    f("comments",      "Comments",                "number"),
    f("shares",        "Shares",                  "number"),
    f("saves",         "Saves",                   "number"),
    f("leads",         "Leads generated",         "number"),
    f("booked",        "Sessions booked",         "number"),
    f("revenue",       "Revenue attributed ($)",  "currency"),
    f("notes",         "Notes",                   "textarea"),
  ],
  followups: [
    f("name", "Follow-up", "text", { title: true }), f("clientId", "Client", "relation", { target: "clients" }),
    f("stage", "Stage", "select", { options: STATUS }), f("futype", "Follow-up type", "select", { options: FUTYPE }),
    f("lastContact", "Last contact", "date"), f("nextAction", "Next action", "date"), f("outcome", "Outcome", "textarea"),
  ],
  referrals: [
    f("referrerId", "Referred by (client)", "relation", { target: "clients" }),
    f("referredName", "Referred person", "text", { title: true }),
    f("referredId", "Referred client (if joined)", "relation", { target: "clients" }),
    f("date", "Referral date", "date"),
    f("status", "Status", "select", { options: REF_STATUS }),
    f("revenue", "Revenue from referral", "currency"),
    f("thankYouSent", "Thank-you sent?", "checkbox"),
    f("rewardGiven", "Reward given?", "checkbox"),
    f("notes", "Notes", "textarea"),
  ],
  outreach: [
    f("name",             "Target / org name",    "text",     { title: true }),
    f("targetType",       "Target type",          "select",   { options: OUTREACH_TARGET_TYPE }),
    f("contactName",      "Contact person",       "text"),
    f("email",            "Email",                "email"),
    f("phone",            "Phone",                "text"),
    f("location",         "Location",             "text"),
    f("source",           "How found",            "select",   { options: OUTREACH_SOURCE }),
    f("painPoint",        "Pain point",           "textarea"),
    f("proposedPackage",  "Proposed package",     "text"),
    f("warmth",           "Relationship warmth",  "select",   { options: OUTREACH_WARMTH }),
    f("priority",         "Priority",             "select",   { options: OUTREACH_PRIORITY }),
    f("status",           "Contact status",       "select",   { options: OUTREACH_STATUS }),
    f("responseStatus",   "Response status",      "select",   { options: OUTREACH_RESPONSE }),
    f("outreachMessage",  "Message / script used","textarea"),
    f("lastContact",      "Last contact date",    "date"),
    f("nextFollowUp",     "Next follow-up date",  "date"),
    f("revenuePotential", "Revenue potential",    "currency"),
    f("partnerId",        "Linked studio partner","relation",  { target: "partners" }),
    f("notes",            "Notes",                "textarea"),
  ],
  testimonials: [
    f("name",            "Testimonial title",      "text",       { title: true }),
    f("clientId",        "Client",                 "relation",   { target: "clients" }),
    f("sessionId",       "Session attended",       "relation",   { target: "sessions" }),
    f("status",          "Status",                 "select",     { options: TESTIMONIAL_STATUS }),
    f("type",            "Type",                   "select",     { options: TESTIMONIAL_TYPE }),
    f("content",         "Full testimonial",       "textarea"),
    f("bestQuote",       "Best quote",             "textarea"),
    f("beforeSummary",   "Before (client state)",  "textarea"),
    f("afterSummary",    "After (what shifted)",   "textarea"),
    f("themes",          "Themes",                 "multiselect",{ options: TESTIMONIAL_THEMES }),
    f("permissionReceived","Permission received?", "checkbox"),
    f("useOnWebsite",    "Use on website?",        "checkbox"),
    f("useOnSocial",     "Use on social?",         "checkbox"),
    f("firstNameOnly",   "First name only?",       "checkbox"),
    f("videoUrl",        "Video URL",              "text"),
    f("dateReceived",    "Date received",          "date"),
    f("datePublished",   "Date published",         "date"),
    f("notes",           "Notes",                  "textarea"),
  ],
  templates: [
    f("name",      "Template name",      "text",     { title: true }),
    f("subject",   "Email subject line", "text"),
    f("body",      "Message body",       "textarea", { rows: 9 }),
    f("notes",     "Notes / usage tips", "textarea"),
    f("variables", "Variables (e.g. {{clientName}})", "text"),
    f("category",  "Category",           "select",   { options: TMPL_CATEGORY }),
    f("channel",   "Channel",            "select",   { options: TMPL_CHANNEL }),
    f("linkedTo",  "Linked to",          "select",   { options: TMPL_LINKED_TO }),
  ],
  expenses: [
    f("date",          "Date",             "date",     { title: true }),
    f("vendor",        "Vendor / Payee",   "text"),
    f("description",   "Description",      "text"),
    f("amount",        "Amount ($)",       "number"),
    f("category",      "Category",         "select",   { options: EXPENSE_CATEGORY }),
    f("paymentMethod", "Payment Method",   "select",   { options: EXPENSE_PAYMENT_METHOD }),
    f("taxDeductible", "Tax Deductible?",  "checkbox"),
    f("recurring",     "Recurring?",       "checkbox"),
    f("recurringFreq", "Frequency",        "select",   { options: EXPENSE_RECUR_FREQ }),
    f("linkedSession", "Linked Session",   "text"),
    f("linkedPartner", "Linked Studio",    "text"),
    f("receiptUrl",    "Receipt URL",      "text"),
    f("stripeRefundId","Stripe Refund ID", "text"),
    f("notes",         "Notes",            "textarea"),
  ],
  registrations: [
    f("eventName",      "Event / Session Name",        "text",     { title: true }),
    f("clientId",       "Client",                      "relation", { target: "clients" }),
    f("status",         "Booking Status",              "select",   { options: ["booked", "attended", "canceled", "rescheduled", "no_show"] }),
    f("paymentAmount",  "Session Price ($)",           "number"),
    f("paymentStatus",  "Payment Status",              "select",   { options: ["paid", "pending_verification", "unmatched", "unpaid", "partial_refund", "refunded", "failed", "unknown"] }),
    f("paidAmount",     "Stripe Amount Paid ($)",      "number"),
    f("paidAt",         "Stripe Paid At",              "text"),
    f("stripeVerified", "Stripe Verified?",            "checkbox"),
    f("stripePaymentIntentId", "Stripe Payment Intent ID", "text"),
    f("stripeChargeId", "Stripe Charge ID",            "text"),
    f("paymentId",      "Linked Payment Record",       "text"),
    f("amountRefunded", "Amount Refunded ($)",         "number"),
    f("stripeRefundId", "Stripe Refund ID",            "text"),
    f("refundedAt",     "Refunded At",                 "text"),
    f("waiverStatus",   "Waiver Status",               "select",   { options: ["pending", "signed"] }),
    f("createdAt",      "Scheduled On",                "text"),
    f("scheduledAt",    "Session Date/Time",           "text"),
    f("timezone",       "Timezone",                    "text"),
    f("locationType",   "Location Type",               "select",   { options: ["zoom", "physical", "custom", "phone", "other"] }),
    f("locationJoinUrl","Zoom / Join URL",             "text"),
    f("locationAddress","In-Person Address",           "text"),
    f("attendanceType", "Attending Virtually or In Person", "text"),
    f("checkedIn",      "Checked In?",                 "checkbox"),
    f("attended",       "Attended?",                   "checkbox"),
    f("noShow",         "No Show?",                    "checkbox"),
    f("doneBreathworkBefore", "Done Breathwork Before?", "text"),
    f("howHeard",       "How Did They Hear About Us?", "text"),
    f("referredBy",     "Referred By",                 "text"),
    f("concerns",       "Physical / Emotional Concerns", "textarea"),
    f("reviewedContraindications", "Reviewed Contraindications?", "text"),
    f("calendlyInviteeUri", "Calendly Invitee URI",    "text"),
    f("calendlyEventUri",   "Calendly Event URI",      "text"),
    f("notes",          "Notes",                       "textarea"),
  ],
};
